# Makefile.in generated by automake 1.11 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008, 2009  Free Software Foundation,
# Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.





pkgdatadir = $(datadir)/isg_cached
pkgincludedir = $(includedir)/isg_cached
pkglibdir = $(libdir)/isg_cached
pkglibexecdir = $(libexecdir)/isg_cached
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
bin_PROGRAMS = isg_cached$(EXEEXT)
subdir = .
DIST_COMMON = README $(am__configure_deps) $(srcdir)/Makefile.am \
	$(srcdir)/Makefile.in $(srcdir)/config.h.in \
	$(top_srcdir)/configure AUTHORS NEWS depcomp install-sh \
	missing
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/m4/ax_lib_oracle_oci.m4 \
	$(top_srcdir)/configure.in
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__installdirs = "$(DESTDIR)$(bindir)" "$(DESTDIR)$(isg_cacheddir)"
PROGRAMS = $(bin_PROGRAMS)
am_isg_cached_OBJECTS = main.$(OBJEXT) isg_cached.$(OBJEXT) \
	billing.$(OBJEXT) queryresult.$(OBJEXT) radpacket.$(OBJEXT) \
	dictionary.$(OBJEXT) coapacket.$(OBJEXT) radclient.$(OBJEXT) \
	listener.$(OBJEXT) coa.$(OBJEXT) oracle.$(OBJEXT) \
	dispatcher.$(OBJEXT) configuration.$(OBJEXT)
isg_cached_OBJECTS = $(am_isg_cached_OBJECTS)
am__DEPENDENCIES_1 =
isg_cached_DEPENDENCIES = $(am__DEPENDENCIES_1) $(am__DEPENDENCIES_1) \
	$(am__DEPENDENCIES_1)
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
CXXLD = $(CXX)
CXXLINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) \
	-o $@
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
SOURCES = $(isg_cached_SOURCES)
DIST_SOURCES = $(isg_cached_SOURCES)
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
DATA = $(isg_cached_DATA)
ETAGS = etags
CTAGS = ctags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  { test ! -d "$(distdir)" \
    || { find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
         && rm -fr "$(distdir)"; }; }
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
distuninstallcheck_listfiles = find . -type f -print
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /home/om/workspace/isg_cached/missing --run aclocal-1.11
AMTAR = ${SHELL} /home/om/workspace/isg_cached/missing --run tar
AUTOCONF = ${SHELL} /home/om/workspace/isg_cached/missing --run autoconf
AUTOHEADER = ${SHELL} /home/om/workspace/isg_cached/missing --run autoheader
AUTOMAKE = ${SHELL} /home/om/workspace/isg_cached/missing --run automake-1.11
AWK = gawk
CPPFLAGS = 
CXX = g++
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EXEEXT = 
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS = 
LIBOBJS = 
LIBS = 
LTLIBOBJS = 
MAKEINFO = ${SHELL} /home/om/workspace/isg_cached/missing --run makeinfo
MEMCACHED_CFLAGS = -I/usr/local/include  
MEMCACHED_LIBS = -L/usr/local/lib -lmemcached  
MKDIR_P = /bin/mkdir -p
OBJEXT = o
ORACLE_OCI_CFLAGS = -I/usr/include/oracle/11.2/client/
ORACLE_OCI_LDFLAGS = -L/usr/lib/oracle/11.2/client/lib -lclntsh
ORACLE_OCI_VERSION = 
PACKAGE = isg_cached
PACKAGE_BUGREPORT = omever@gmail.com
PACKAGE_NAME = isg_cached
PACKAGE_STRING = isg_cached 1.2
PACKAGE_TARNAME = isg_cached
PACKAGE_VERSION = 1.2
PATH_SEPARATOR = :
PKG_CONFIG = /usr/bin/pkg-config
SET_MAKE = 
SHELL = /bin/sh
STRIP = 
VERSION = 1.2
XML_CFLAGS = -I/usr/include/libxml2  
XML_LIBS = -lxml2  
abs_builddir = /home/om/workspace/isg_cached
abs_srcdir = /home/om/workspace/isg_cached
abs_top_builddir = /home/om/workspace/isg_cached
abs_top_srcdir = /home/om/workspace/isg_cached
ac_ct_CXX = g++
am__include = include
am__leading_dot = .
am__quote = 
am__tar = ${AMTAR} chof - "$$tardir"
am__untar = ${AMTAR} xf -
bindir = ${exec_prefix}/bin
build_alias = 
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host_alias = 
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/om/workspace/isg_cached/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = /bin/mkdir -p
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
AM_CXXFLAGS = -DDATADIR='"$(datadir)"' -Isrc -Isrc/dispatcher -Isrc/oracle -Isrc/radius $(ORACLE_OCI_CFLAGS) $(XML_CFLAGS) $(MEMCACHED_CFLAGS) -I/usr/local/include/libmemcached
ACLOCAL_AMFLAGS = -I m4
# find * -name \*.h -or -name \*.cpp | xargs echo
isg_cached_SOURCES = config.h src/listener.h src/main.cpp src/isg_cached.cpp src/oracle/billing.h src/oracle/billing.cpp src/oracle/queryresult.h src/oracle/queryresult.cpp src/radius/radclient.h src/radius/coapacket.h src/radius/radpacket.cpp src/radius/radpacket.h src/radius/dictionary.cpp src/radius/dictionary.h src/radius/coapacket.cpp src/radius/radclient.cpp src/listener.cpp src/dispatcher/coa.cpp src/dispatcher/oracle.cpp src/dispatcher/coa.h src/dispatcher/dispatcher.cpp src/dispatcher/oracle.h src/dispatcher/dispatcher.h src/configuration.h src/configuration.cpp
isg_cached_LDADD = -locci -lclntsh -lxml2 -lmemcached -lssl -lpthread -liniparser $(ORACLE_OCI_LDFLAGS) $(XML_LIBS) $(MEMCACHED_LIBS)
isg_cached_DATA = radius/dictionary
isg_cacheddir = $(datadir)/isg_cached/radius
all: config.h
	$(MAKE) $(AM_MAKEFLAGS) all-am

.SUFFIXES:
.SUFFIXES: .cpp .o .obj
am--refresh:
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

config.h: stamp-h1
	@if test ! -f $@; then \
	  rm -f stamp-h1; \
	  $(MAKE) $(AM_MAKEFLAGS) stamp-h1; \
	else :; fi

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h
$(srcdir)/config.h.in:  $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f config.h stamp-h1
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	test -z "$(bindir)" || $(MKDIR_P) "$(DESTDIR)$(bindir)"
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p; \
	  then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	      echo " $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	      $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' `; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)
isg_cached$(EXEEXT): $(isg_cached_OBJECTS) $(isg_cached_DEPENDENCIES) 
	@rm -f isg_cached$(EXEEXT)
	$(CXXLINK) $(isg_cached_OBJECTS) $(isg_cached_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/billing.Po
include ./$(DEPDIR)/coa.Po
include ./$(DEPDIR)/coapacket.Po
include ./$(DEPDIR)/configuration.Po
include ./$(DEPDIR)/dictionary.Po
include ./$(DEPDIR)/dispatcher.Po
include ./$(DEPDIR)/isg_cached.Po
include ./$(DEPDIR)/listener.Po
include ./$(DEPDIR)/main.Po
include ./$(DEPDIR)/oracle.Po
include ./$(DEPDIR)/queryresult.Po
include ./$(DEPDIR)/radclient.Po
include ./$(DEPDIR)/radpacket.Po

.cpp.o:
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ $<

.cpp.obj:
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

main.o: src/main.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT main.o -MD -MP -MF $(DEPDIR)/main.Tpo -c -o main.o `test -f 'src/main.cpp' || echo '$(srcdir)/'`src/main.cpp
	$(am__mv) $(DEPDIR)/main.Tpo $(DEPDIR)/main.Po
#	source='src/main.cpp' object='main.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o main.o `test -f 'src/main.cpp' || echo '$(srcdir)/'`src/main.cpp

main.obj: src/main.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT main.obj -MD -MP -MF $(DEPDIR)/main.Tpo -c -o main.obj `if test -f 'src/main.cpp'; then $(CYGPATH_W) 'src/main.cpp'; else $(CYGPATH_W) '$(srcdir)/src/main.cpp'; fi`
	$(am__mv) $(DEPDIR)/main.Tpo $(DEPDIR)/main.Po
#	source='src/main.cpp' object='main.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o main.obj `if test -f 'src/main.cpp'; then $(CYGPATH_W) 'src/main.cpp'; else $(CYGPATH_W) '$(srcdir)/src/main.cpp'; fi`

isg_cached.o: src/isg_cached.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT isg_cached.o -MD -MP -MF $(DEPDIR)/isg_cached.Tpo -c -o isg_cached.o `test -f 'src/isg_cached.cpp' || echo '$(srcdir)/'`src/isg_cached.cpp
	$(am__mv) $(DEPDIR)/isg_cached.Tpo $(DEPDIR)/isg_cached.Po
#	source='src/isg_cached.cpp' object='isg_cached.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o isg_cached.o `test -f 'src/isg_cached.cpp' || echo '$(srcdir)/'`src/isg_cached.cpp

isg_cached.obj: src/isg_cached.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT isg_cached.obj -MD -MP -MF $(DEPDIR)/isg_cached.Tpo -c -o isg_cached.obj `if test -f 'src/isg_cached.cpp'; then $(CYGPATH_W) 'src/isg_cached.cpp'; else $(CYGPATH_W) '$(srcdir)/src/isg_cached.cpp'; fi`
	$(am__mv) $(DEPDIR)/isg_cached.Tpo $(DEPDIR)/isg_cached.Po
#	source='src/isg_cached.cpp' object='isg_cached.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o isg_cached.obj `if test -f 'src/isg_cached.cpp'; then $(CYGPATH_W) 'src/isg_cached.cpp'; else $(CYGPATH_W) '$(srcdir)/src/isg_cached.cpp'; fi`

billing.o: src/oracle/billing.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT billing.o -MD -MP -MF $(DEPDIR)/billing.Tpo -c -o billing.o `test -f 'src/oracle/billing.cpp' || echo '$(srcdir)/'`src/oracle/billing.cpp
	$(am__mv) $(DEPDIR)/billing.Tpo $(DEPDIR)/billing.Po
#	source='src/oracle/billing.cpp' object='billing.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o billing.o `test -f 'src/oracle/billing.cpp' || echo '$(srcdir)/'`src/oracle/billing.cpp

billing.obj: src/oracle/billing.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT billing.obj -MD -MP -MF $(DEPDIR)/billing.Tpo -c -o billing.obj `if test -f 'src/oracle/billing.cpp'; then $(CYGPATH_W) 'src/oracle/billing.cpp'; else $(CYGPATH_W) '$(srcdir)/src/oracle/billing.cpp'; fi`
	$(am__mv) $(DEPDIR)/billing.Tpo $(DEPDIR)/billing.Po
#	source='src/oracle/billing.cpp' object='billing.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o billing.obj `if test -f 'src/oracle/billing.cpp'; then $(CYGPATH_W) 'src/oracle/billing.cpp'; else $(CYGPATH_W) '$(srcdir)/src/oracle/billing.cpp'; fi`

queryresult.o: src/oracle/queryresult.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT queryresult.o -MD -MP -MF $(DEPDIR)/queryresult.Tpo -c -o queryresult.o `test -f 'src/oracle/queryresult.cpp' || echo '$(srcdir)/'`src/oracle/queryresult.cpp
	$(am__mv) $(DEPDIR)/queryresult.Tpo $(DEPDIR)/queryresult.Po
#	source='src/oracle/queryresult.cpp' object='queryresult.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o queryresult.o `test -f 'src/oracle/queryresult.cpp' || echo '$(srcdir)/'`src/oracle/queryresult.cpp

queryresult.obj: src/oracle/queryresult.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT queryresult.obj -MD -MP -MF $(DEPDIR)/queryresult.Tpo -c -o queryresult.obj `if test -f 'src/oracle/queryresult.cpp'; then $(CYGPATH_W) 'src/oracle/queryresult.cpp'; else $(CYGPATH_W) '$(srcdir)/src/oracle/queryresult.cpp'; fi`
	$(am__mv) $(DEPDIR)/queryresult.Tpo $(DEPDIR)/queryresult.Po
#	source='src/oracle/queryresult.cpp' object='queryresult.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o queryresult.obj `if test -f 'src/oracle/queryresult.cpp'; then $(CYGPATH_W) 'src/oracle/queryresult.cpp'; else $(CYGPATH_W) '$(srcdir)/src/oracle/queryresult.cpp'; fi`

radpacket.o: src/radius/radpacket.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT radpacket.o -MD -MP -MF $(DEPDIR)/radpacket.Tpo -c -o radpacket.o `test -f 'src/radius/radpacket.cpp' || echo '$(srcdir)/'`src/radius/radpacket.cpp
	$(am__mv) $(DEPDIR)/radpacket.Tpo $(DEPDIR)/radpacket.Po
#	source='src/radius/radpacket.cpp' object='radpacket.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o radpacket.o `test -f 'src/radius/radpacket.cpp' || echo '$(srcdir)/'`src/radius/radpacket.cpp

radpacket.obj: src/radius/radpacket.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT radpacket.obj -MD -MP -MF $(DEPDIR)/radpacket.Tpo -c -o radpacket.obj `if test -f 'src/radius/radpacket.cpp'; then $(CYGPATH_W) 'src/radius/radpacket.cpp'; else $(CYGPATH_W) '$(srcdir)/src/radius/radpacket.cpp'; fi`
	$(am__mv) $(DEPDIR)/radpacket.Tpo $(DEPDIR)/radpacket.Po
#	source='src/radius/radpacket.cpp' object='radpacket.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o radpacket.obj `if test -f 'src/radius/radpacket.cpp'; then $(CYGPATH_W) 'src/radius/radpacket.cpp'; else $(CYGPATH_W) '$(srcdir)/src/radius/radpacket.cpp'; fi`

dictionary.o: src/radius/dictionary.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT dictionary.o -MD -MP -MF $(DEPDIR)/dictionary.Tpo -c -o dictionary.o `test -f 'src/radius/dictionary.cpp' || echo '$(srcdir)/'`src/radius/dictionary.cpp
	$(am__mv) $(DEPDIR)/dictionary.Tpo $(DEPDIR)/dictionary.Po
#	source='src/radius/dictionary.cpp' object='dictionary.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o dictionary.o `test -f 'src/radius/dictionary.cpp' || echo '$(srcdir)/'`src/radius/dictionary.cpp

dictionary.obj: src/radius/dictionary.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT dictionary.obj -MD -MP -MF $(DEPDIR)/dictionary.Tpo -c -o dictionary.obj `if test -f 'src/radius/dictionary.cpp'; then $(CYGPATH_W) 'src/radius/dictionary.cpp'; else $(CYGPATH_W) '$(srcdir)/src/radius/dictionary.cpp'; fi`
	$(am__mv) $(DEPDIR)/dictionary.Tpo $(DEPDIR)/dictionary.Po
#	source='src/radius/dictionary.cpp' object='dictionary.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o dictionary.obj `if test -f 'src/radius/dictionary.cpp'; then $(CYGPATH_W) 'src/radius/dictionary.cpp'; else $(CYGPATH_W) '$(srcdir)/src/radius/dictionary.cpp'; fi`

coapacket.o: src/radius/coapacket.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT coapacket.o -MD -MP -MF $(DEPDIR)/coapacket.Tpo -c -o coapacket.o `test -f 'src/radius/coapacket.cpp' || echo '$(srcdir)/'`src/radius/coapacket.cpp
	$(am__mv) $(DEPDIR)/coapacket.Tpo $(DEPDIR)/coapacket.Po
#	source='src/radius/coapacket.cpp' object='coapacket.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o coapacket.o `test -f 'src/radius/coapacket.cpp' || echo '$(srcdir)/'`src/radius/coapacket.cpp

coapacket.obj: src/radius/coapacket.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT coapacket.obj -MD -MP -MF $(DEPDIR)/coapacket.Tpo -c -o coapacket.obj `if test -f 'src/radius/coapacket.cpp'; then $(CYGPATH_W) 'src/radius/coapacket.cpp'; else $(CYGPATH_W) '$(srcdir)/src/radius/coapacket.cpp'; fi`
	$(am__mv) $(DEPDIR)/coapacket.Tpo $(DEPDIR)/coapacket.Po
#	source='src/radius/coapacket.cpp' object='coapacket.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o coapacket.obj `if test -f 'src/radius/coapacket.cpp'; then $(CYGPATH_W) 'src/radius/coapacket.cpp'; else $(CYGPATH_W) '$(srcdir)/src/radius/coapacket.cpp'; fi`

radclient.o: src/radius/radclient.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT radclient.o -MD -MP -MF $(DEPDIR)/radclient.Tpo -c -o radclient.o `test -f 'src/radius/radclient.cpp' || echo '$(srcdir)/'`src/radius/radclient.cpp
	$(am__mv) $(DEPDIR)/radclient.Tpo $(DEPDIR)/radclient.Po
#	source='src/radius/radclient.cpp' object='radclient.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o radclient.o `test -f 'src/radius/radclient.cpp' || echo '$(srcdir)/'`src/radius/radclient.cpp

radclient.obj: src/radius/radclient.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT radclient.obj -MD -MP -MF $(DEPDIR)/radclient.Tpo -c -o radclient.obj `if test -f 'src/radius/radclient.cpp'; then $(CYGPATH_W) 'src/radius/radclient.cpp'; else $(CYGPATH_W) '$(srcdir)/src/radius/radclient.cpp'; fi`
	$(am__mv) $(DEPDIR)/radclient.Tpo $(DEPDIR)/radclient.Po
#	source='src/radius/radclient.cpp' object='radclient.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o radclient.obj `if test -f 'src/radius/radclient.cpp'; then $(CYGPATH_W) 'src/radius/radclient.cpp'; else $(CYGPATH_W) '$(srcdir)/src/radius/radclient.cpp'; fi`

listener.o: src/listener.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT listener.o -MD -MP -MF $(DEPDIR)/listener.Tpo -c -o listener.o `test -f 'src/listener.cpp' || echo '$(srcdir)/'`src/listener.cpp
	$(am__mv) $(DEPDIR)/listener.Tpo $(DEPDIR)/listener.Po
#	source='src/listener.cpp' object='listener.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o listener.o `test -f 'src/listener.cpp' || echo '$(srcdir)/'`src/listener.cpp

listener.obj: src/listener.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT listener.obj -MD -MP -MF $(DEPDIR)/listener.Tpo -c -o listener.obj `if test -f 'src/listener.cpp'; then $(CYGPATH_W) 'src/listener.cpp'; else $(CYGPATH_W) '$(srcdir)/src/listener.cpp'; fi`
	$(am__mv) $(DEPDIR)/listener.Tpo $(DEPDIR)/listener.Po
#	source='src/listener.cpp' object='listener.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o listener.obj `if test -f 'src/listener.cpp'; then $(CYGPATH_W) 'src/listener.cpp'; else $(CYGPATH_W) '$(srcdir)/src/listener.cpp'; fi`

coa.o: src/dispatcher/coa.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT coa.o -MD -MP -MF $(DEPDIR)/coa.Tpo -c -o coa.o `test -f 'src/dispatcher/coa.cpp' || echo '$(srcdir)/'`src/dispatcher/coa.cpp
	$(am__mv) $(DEPDIR)/coa.Tpo $(DEPDIR)/coa.Po
#	source='src/dispatcher/coa.cpp' object='coa.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o coa.o `test -f 'src/dispatcher/coa.cpp' || echo '$(srcdir)/'`src/dispatcher/coa.cpp

coa.obj: src/dispatcher/coa.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT coa.obj -MD -MP -MF $(DEPDIR)/coa.Tpo -c -o coa.obj `if test -f 'src/dispatcher/coa.cpp'; then $(CYGPATH_W) 'src/dispatcher/coa.cpp'; else $(CYGPATH_W) '$(srcdir)/src/dispatcher/coa.cpp'; fi`
	$(am__mv) $(DEPDIR)/coa.Tpo $(DEPDIR)/coa.Po
#	source='src/dispatcher/coa.cpp' object='coa.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o coa.obj `if test -f 'src/dispatcher/coa.cpp'; then $(CYGPATH_W) 'src/dispatcher/coa.cpp'; else $(CYGPATH_W) '$(srcdir)/src/dispatcher/coa.cpp'; fi`

oracle.o: src/dispatcher/oracle.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT oracle.o -MD -MP -MF $(DEPDIR)/oracle.Tpo -c -o oracle.o `test -f 'src/dispatcher/oracle.cpp' || echo '$(srcdir)/'`src/dispatcher/oracle.cpp
	$(am__mv) $(DEPDIR)/oracle.Tpo $(DEPDIR)/oracle.Po
#	source='src/dispatcher/oracle.cpp' object='oracle.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o oracle.o `test -f 'src/dispatcher/oracle.cpp' || echo '$(srcdir)/'`src/dispatcher/oracle.cpp

oracle.obj: src/dispatcher/oracle.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT oracle.obj -MD -MP -MF $(DEPDIR)/oracle.Tpo -c -o oracle.obj `if test -f 'src/dispatcher/oracle.cpp'; then $(CYGPATH_W) 'src/dispatcher/oracle.cpp'; else $(CYGPATH_W) '$(srcdir)/src/dispatcher/oracle.cpp'; fi`
	$(am__mv) $(DEPDIR)/oracle.Tpo $(DEPDIR)/oracle.Po
#	source='src/dispatcher/oracle.cpp' object='oracle.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o oracle.obj `if test -f 'src/dispatcher/oracle.cpp'; then $(CYGPATH_W) 'src/dispatcher/oracle.cpp'; else $(CYGPATH_W) '$(srcdir)/src/dispatcher/oracle.cpp'; fi`

dispatcher.o: src/dispatcher/dispatcher.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT dispatcher.o -MD -MP -MF $(DEPDIR)/dispatcher.Tpo -c -o dispatcher.o `test -f 'src/dispatcher/dispatcher.cpp' || echo '$(srcdir)/'`src/dispatcher/dispatcher.cpp
	$(am__mv) $(DEPDIR)/dispatcher.Tpo $(DEPDIR)/dispatcher.Po
#	source='src/dispatcher/dispatcher.cpp' object='dispatcher.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o dispatcher.o `test -f 'src/dispatcher/dispatcher.cpp' || echo '$(srcdir)/'`src/dispatcher/dispatcher.cpp

dispatcher.obj: src/dispatcher/dispatcher.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT dispatcher.obj -MD -MP -MF $(DEPDIR)/dispatcher.Tpo -c -o dispatcher.obj `if test -f 'src/dispatcher/dispatcher.cpp'; then $(CYGPATH_W) 'src/dispatcher/dispatcher.cpp'; else $(CYGPATH_W) '$(srcdir)/src/dispatcher/dispatcher.cpp'; fi`
	$(am__mv) $(DEPDIR)/dispatcher.Tpo $(DEPDIR)/dispatcher.Po
#	source='src/dispatcher/dispatcher.cpp' object='dispatcher.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o dispatcher.obj `if test -f 'src/dispatcher/dispatcher.cpp'; then $(CYGPATH_W) 'src/dispatcher/dispatcher.cpp'; else $(CYGPATH_W) '$(srcdir)/src/dispatcher/dispatcher.cpp'; fi`

configuration.o: src/configuration.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT configuration.o -MD -MP -MF $(DEPDIR)/configuration.Tpo -c -o configuration.o `test -f 'src/configuration.cpp' || echo '$(srcdir)/'`src/configuration.cpp
	$(am__mv) $(DEPDIR)/configuration.Tpo $(DEPDIR)/configuration.Po
#	source='src/configuration.cpp' object='configuration.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o configuration.o `test -f 'src/configuration.cpp' || echo '$(srcdir)/'`src/configuration.cpp

configuration.obj: src/configuration.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT configuration.obj -MD -MP -MF $(DEPDIR)/configuration.Tpo -c -o configuration.obj `if test -f 'src/configuration.cpp'; then $(CYGPATH_W) 'src/configuration.cpp'; else $(CYGPATH_W) '$(srcdir)/src/configuration.cpp'; fi`
	$(am__mv) $(DEPDIR)/configuration.Tpo $(DEPDIR)/configuration.Po
#	source='src/configuration.cpp' object='configuration.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o configuration.obj `if test -f 'src/configuration.cpp'; then $(CYGPATH_W) 'src/configuration.cpp'; else $(CYGPATH_W) '$(srcdir)/src/configuration.cpp'; fi`
install-isg_cachedDATA: $(isg_cached_DATA)
	@$(NORMAL_INSTALL)
	test -z "$(isg_cacheddir)" || $(MKDIR_P) "$(DESTDIR)$(isg_cacheddir)"
	@list='$(isg_cached_DATA)'; test -n "$(isg_cacheddir)" || list=; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(isg_cacheddir)'"; \
	  $(INSTALL_DATA) $$files "$(DESTDIR)$(isg_cacheddir)" || exit $$?; \
	done

uninstall-isg_cachedDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(isg_cached_DATA)'; test -n "$(isg_cacheddir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	test -n "$$files" || exit 0; \
	echo " ( cd '$(DESTDIR)$(isg_cacheddir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(isg_cacheddir)" && rm -f $$files

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS:  $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	set x; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: CTAGS
CTAGS:  $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -777 -exec chmod a+rwx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | bzip2 -9 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

dist-lzma: distdir
	tardir=$(distdir) && $(am__tar) | lzma -9 -c >$(distdir).tar.lzma
	$(am__remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | xz -c >$(distdir).tar.xz
	$(am__remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__remove_distdir)

dist dist-all: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gunzip -c $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bunzip2 -c $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lzma*) \
	  unlzma -c $(distdir).tar.lzma | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gunzip -c $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir); chmod a+w $(distdir)
	mkdir $(distdir)/_build
	mkdir $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@$(am__cd) '$(distuninstallcheck_dir)' \
	&& test `$(distuninstallcheck_listfiles) | wc -l` -le 1 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile $(PROGRAMS) $(DATA) config.h
installdirs:
	for dir in "$(DESTDIR)$(bindir)" "$(DESTDIR)$(isg_cacheddir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am: install-isg_cachedDATA

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS uninstall-isg_cachedDATA

.MAKE: all install-am install-strip

.PHONY: CTAGS GTAGS all all-am am--refresh check check-am clean \
	clean-binPROGRAMS clean-generic ctags dist dist-all dist-bzip2 \
	dist-gzip dist-lzma dist-shar dist-tarZ dist-xz dist-zip \
	distcheck distclean distclean-compile distclean-generic \
	distclean-hdr distclean-tags distcleancheck distdir \
	distuninstallcheck dvi dvi-am html html-am info info-am \
	install install-am install-binPROGRAMS install-data \
	install-data-am install-dvi install-dvi-am install-exec \
	install-exec-am install-html install-html-am install-info \
	install-info-am install-isg_cachedDATA install-man install-pdf \
	install-pdf-am install-ps install-ps-am install-strip \
	installcheck installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic pdf pdf-am ps ps-am tags uninstall \
	uninstall-am uninstall-binPROGRAMS uninstall-isg_cachedDATA


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
